site_name: Experimental Site
site_description: Публикация результатов экспериментов
site_author: Ivan Pogorenko

use_directory_urls: false

markdown_extensions:
  - pymdownx.arithmatex:
      generic: true

extra:
  version:
    provider: mike

extra_javascript:
  - javascripts/mathjax-config.js
  - javascripts/mathjax/es5/tex-chtml.js

theme:
  name: mkdocs

nav:
  - Главная: index.md
  - Эксперименты: experiments.md
  - Результаты: results.md
  - Методика: methodology.md
  - Лицензии: license.md