site_name: Experimental Site
site_description: Публикация результатов экспериментов
site_author: Ivan Pogorenko

site_url: https://0564e481-a60e-48b9-8cfd-ec3fdfca58b1.selstorage.ru/

use_directory_urls: false

markdown_extensions:
  - pymdownx.arithmatex:
      generic: true

plugins:
  - mike:
      alias_type: copy

extra:
  version:
    provider: mike

extra_javascript:
  - javascripts/mathjax-config.js
  - javascripts/mathjax/es5/tex-chtml.js

theme:
  name: mkdocs

nav:
  - Главная: index.md
  - Эксперименты: experiments.md
  - Результаты: results.md
  - Методика: methodology.md
  - Лицензии: license.md